/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterStaffRouteImport } from './routes/register-staff'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthStaffRouteImport } from './routes/_auth/_staff'
import { Route as AuthBossRouteImport } from './routes/_auth/_boss'
import { Route as AuthBossWorkshopRouteImport } from './routes/_auth/_boss/workshop'
import { Route as AuthBossPendingRouteImport } from './routes/_auth/_boss/pending'
import { Route as AuthStaffMyRecordsIndexRouteImport } from './routes/_auth/_staff/my-records/index'
import { Route as AuthBossStaffIndexRouteImport } from './routes/_auth/_boss/staff/index'
import { Route as AuthBossRecordsIndexRouteImport } from './routes/_auth/_boss/records/index'
import { Route as AuthBossOrdersIndexRouteImport } from './routes/_auth/_boss/orders/index'
import { Route as AuthBossCustomersIndexRouteImport } from './routes/_auth/_boss/customers/index'
import { Route as AuthStaffMyRecordsStatsRouteImport } from './routes/_auth/_staff/my-records/stats'
import { Route as AuthStaffMyRecordsNewRouteImport } from './routes/_auth/_staff/my-records/new'
import { Route as AuthStaffMyRecordsIdRouteImport } from './routes/_auth/_staff/my-records/$id'
import { Route as AuthBossRecordsStatsRouteImport } from './routes/_auth/_boss/records/stats'
import { Route as AuthBossRecordsNewRouteImport } from './routes/_auth/_boss/records/new'
import { Route as AuthBossRecordsIdRouteImport } from './routes/_auth/_boss/records/$id'
import { Route as AuthBossOrdersStatsRouteImport } from './routes/_auth/_boss/orders/stats'
import { Route as AuthBossOrdersNewRouteImport } from './routes/_auth/_boss/orders/new'
import { Route as AuthBossCustomersNewRouteImport } from './routes/_auth/_boss/customers/new'
import { Route as AuthBossCustomersIdRouteImport } from './routes/_auth/_boss/customers/$id'
import { Route as AuthBossOrdersIdIndexRouteImport } from './routes/_auth/_boss/orders/$id/index'
import { Route as AuthBossOrdersIdEditRouteImport } from './routes/_auth/_boss/orders/$id/edit'

const RegisterStaffRoute = RegisterStaffRouteImport.update({
  id: '/register-staff',
  path: '/register-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStaffRoute = AuthStaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBossRoute = AuthBossRouteImport.update({
  id: '/_boss',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBossWorkshopRoute = AuthBossWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossPendingRoute = AuthBossPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthStaffMyRecordsIndexRoute = AuthStaffMyRecordsIndexRouteImport.update({
  id: '/my-records/',
  path: '/my-records/',
  getParentRoute: () => AuthStaffRoute,
} as any)
const AuthBossStaffIndexRoute = AuthBossStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossRecordsIndexRoute = AuthBossRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersIndexRoute = AuthBossOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossCustomersIndexRoute = AuthBossCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthStaffMyRecordsStatsRoute = AuthStaffMyRecordsStatsRouteImport.update({
  id: '/my-records/stats',
  path: '/my-records/stats',
  getParentRoute: () => AuthStaffRoute,
} as any)
const AuthStaffMyRecordsNewRoute = AuthStaffMyRecordsNewRouteImport.update({
  id: '/my-records/new',
  path: '/my-records/new',
  getParentRoute: () => AuthStaffRoute,
} as any)
const AuthStaffMyRecordsIdRoute = AuthStaffMyRecordsIdRouteImport.update({
  id: '/my-records/$id',
  path: '/my-records/$id',
  getParentRoute: () => AuthStaffRoute,
} as any)
const AuthBossRecordsStatsRoute = AuthBossRecordsStatsRouteImport.update({
  id: '/records/stats',
  path: '/records/stats',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossRecordsNewRoute = AuthBossRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossRecordsIdRoute = AuthBossRecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersStatsRoute = AuthBossOrdersStatsRouteImport.update({
  id: '/orders/stats',
  path: '/orders/stats',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersNewRoute = AuthBossOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossCustomersNewRoute = AuthBossCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossCustomersIdRoute = AuthBossCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersIdIndexRoute = AuthBossOrdersIdIndexRouteImport.update({
  id: '/orders/$id/',
  path: '/orders/$id/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersIdEditRoute = AuthBossOrdersIdEditRouteImport.update({
  id: '/orders/$id/edit',
  path: '/orders/$id/edit',
  getParentRoute: () => AuthBossRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-staff': typeof RegisterStaffRoute
  '/profile': typeof AuthProfileRoute
  '/': typeof AuthIndexRoute
  '/pending': typeof AuthBossPendingRoute
  '/workshop': typeof AuthBossWorkshopRoute
  '/customers/$id': typeof AuthBossCustomersIdRoute
  '/customers/new': typeof AuthBossCustomersNewRoute
  '/orders/new': typeof AuthBossOrdersNewRoute
  '/orders/stats': typeof AuthBossOrdersStatsRoute
  '/records/$id': typeof AuthBossRecordsIdRoute
  '/records/new': typeof AuthBossRecordsNewRoute
  '/records/stats': typeof AuthBossRecordsStatsRoute
  '/my-records/$id': typeof AuthStaffMyRecordsIdRoute
  '/my-records/new': typeof AuthStaffMyRecordsNewRoute
  '/my-records/stats': typeof AuthStaffMyRecordsStatsRoute
  '/customers': typeof AuthBossCustomersIndexRoute
  '/orders': typeof AuthBossOrdersIndexRoute
  '/records': typeof AuthBossRecordsIndexRoute
  '/staff': typeof AuthBossStaffIndexRoute
  '/my-records': typeof AuthStaffMyRecordsIndexRoute
  '/orders/$id/edit': typeof AuthBossOrdersIdEditRoute
  '/orders/$id': typeof AuthBossOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-staff': typeof RegisterStaffRoute
  '/profile': typeof AuthProfileRoute
  '/': typeof AuthIndexRoute
  '/pending': typeof AuthBossPendingRoute
  '/workshop': typeof AuthBossWorkshopRoute
  '/customers/$id': typeof AuthBossCustomersIdRoute
  '/customers/new': typeof AuthBossCustomersNewRoute
  '/orders/new': typeof AuthBossOrdersNewRoute
  '/orders/stats': typeof AuthBossOrdersStatsRoute
  '/records/$id': typeof AuthBossRecordsIdRoute
  '/records/new': typeof AuthBossRecordsNewRoute
  '/records/stats': typeof AuthBossRecordsStatsRoute
  '/my-records/$id': typeof AuthStaffMyRecordsIdRoute
  '/my-records/new': typeof AuthStaffMyRecordsNewRoute
  '/my-records/stats': typeof AuthStaffMyRecordsStatsRoute
  '/customers': typeof AuthBossCustomersIndexRoute
  '/orders': typeof AuthBossOrdersIndexRoute
  '/records': typeof AuthBossRecordsIndexRoute
  '/staff': typeof AuthBossStaffIndexRoute
  '/my-records': typeof AuthStaffMyRecordsIndexRoute
  '/orders/$id/edit': typeof AuthBossOrdersIdEditRoute
  '/orders/$id': typeof AuthBossOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-staff': typeof RegisterStaffRoute
  '/_auth/_boss': typeof AuthBossRouteWithChildren
  '/_auth/_staff': typeof AuthStaffRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/_boss/pending': typeof AuthBossPendingRoute
  '/_auth/_boss/workshop': typeof AuthBossWorkshopRoute
  '/_auth/_boss/customers/$id': typeof AuthBossCustomersIdRoute
  '/_auth/_boss/customers/new': typeof AuthBossCustomersNewRoute
  '/_auth/_boss/orders/new': typeof AuthBossOrdersNewRoute
  '/_auth/_boss/orders/stats': typeof AuthBossOrdersStatsRoute
  '/_auth/_boss/records/$id': typeof AuthBossRecordsIdRoute
  '/_auth/_boss/records/new': typeof AuthBossRecordsNewRoute
  '/_auth/_boss/records/stats': typeof AuthBossRecordsStatsRoute
  '/_auth/_staff/my-records/$id': typeof AuthStaffMyRecordsIdRoute
  '/_auth/_staff/my-records/new': typeof AuthStaffMyRecordsNewRoute
  '/_auth/_staff/my-records/stats': typeof AuthStaffMyRecordsStatsRoute
  '/_auth/_boss/customers/': typeof AuthBossCustomersIndexRoute
  '/_auth/_boss/orders/': typeof AuthBossOrdersIndexRoute
  '/_auth/_boss/records/': typeof AuthBossRecordsIndexRoute
  '/_auth/_boss/staff/': typeof AuthBossStaffIndexRoute
  '/_auth/_staff/my-records/': typeof AuthStaffMyRecordsIndexRoute
  '/_auth/_boss/orders/$id/edit': typeof AuthBossOrdersIdEditRoute
  '/_auth/_boss/orders/$id/': typeof AuthBossOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/register-staff'
    | '/profile'
    | '/'
    | '/pending'
    | '/workshop'
    | '/customers/$id'
    | '/customers/new'
    | '/orders/new'
    | '/orders/stats'
    | '/records/$id'
    | '/records/new'
    | '/records/stats'
    | '/my-records/$id'
    | '/my-records/new'
    | '/my-records/stats'
    | '/customers'
    | '/orders'
    | '/records'
    | '/staff'
    | '/my-records'
    | '/orders/$id/edit'
    | '/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/register-staff'
    | '/profile'
    | '/'
    | '/pending'
    | '/workshop'
    | '/customers/$id'
    | '/customers/new'
    | '/orders/new'
    | '/orders/stats'
    | '/records/$id'
    | '/records/new'
    | '/records/stats'
    | '/my-records/$id'
    | '/my-records/new'
    | '/my-records/stats'
    | '/customers'
    | '/orders'
    | '/records'
    | '/staff'
    | '/my-records'
    | '/orders/$id/edit'
    | '/orders/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/register-staff'
    | '/_auth/_boss'
    | '/_auth/_staff'
    | '/_auth/profile'
    | '/_auth/'
    | '/_auth/_boss/pending'
    | '/_auth/_boss/workshop'
    | '/_auth/_boss/customers/$id'
    | '/_auth/_boss/customers/new'
    | '/_auth/_boss/orders/new'
    | '/_auth/_boss/orders/stats'
    | '/_auth/_boss/records/$id'
    | '/_auth/_boss/records/new'
    | '/_auth/_boss/records/stats'
    | '/_auth/_staff/my-records/$id'
    | '/_auth/_staff/my-records/new'
    | '/_auth/_staff/my-records/stats'
    | '/_auth/_boss/customers/'
    | '/_auth/_boss/orders/'
    | '/_auth/_boss/records/'
    | '/_auth/_boss/staff/'
    | '/_auth/_staff/my-records/'
    | '/_auth/_boss/orders/$id/edit'
    | '/_auth/_boss/orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterStaffRoute: typeof RegisterStaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-staff': {
      id: '/register-staff'
      path: '/register-staff'
      fullPath: '/register-staff'
      preLoaderRoute: typeof RegisterStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_staff': {
      id: '/_auth/_staff'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthStaffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_boss': {
      id: '/_auth/_boss'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthBossRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_boss/workshop': {
      id: '/_auth/_boss/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof AuthBossWorkshopRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/pending': {
      id: '/_auth/_boss/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthBossPendingRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_staff/my-records/': {
      id: '/_auth/_staff/my-records/'
      path: '/my-records'
      fullPath: '/my-records'
      preLoaderRoute: typeof AuthStaffMyRecordsIndexRouteImport
      parentRoute: typeof AuthStaffRoute
    }
    '/_auth/_boss/staff/': {
      id: '/_auth/_boss/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthBossStaffIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/records/': {
      id: '/_auth/_boss/records/'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthBossRecordsIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/': {
      id: '/_auth/_boss/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthBossOrdersIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/customers/': {
      id: '/_auth/_boss/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthBossCustomersIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_staff/my-records/stats': {
      id: '/_auth/_staff/my-records/stats'
      path: '/my-records/stats'
      fullPath: '/my-records/stats'
      preLoaderRoute: typeof AuthStaffMyRecordsStatsRouteImport
      parentRoute: typeof AuthStaffRoute
    }
    '/_auth/_staff/my-records/new': {
      id: '/_auth/_staff/my-records/new'
      path: '/my-records/new'
      fullPath: '/my-records/new'
      preLoaderRoute: typeof AuthStaffMyRecordsNewRouteImport
      parentRoute: typeof AuthStaffRoute
    }
    '/_auth/_staff/my-records/$id': {
      id: '/_auth/_staff/my-records/$id'
      path: '/my-records/$id'
      fullPath: '/my-records/$id'
      preLoaderRoute: typeof AuthStaffMyRecordsIdRouteImport
      parentRoute: typeof AuthStaffRoute
    }
    '/_auth/_boss/records/stats': {
      id: '/_auth/_boss/records/stats'
      path: '/records/stats'
      fullPath: '/records/stats'
      preLoaderRoute: typeof AuthBossRecordsStatsRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/records/new': {
      id: '/_auth/_boss/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof AuthBossRecordsNewRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/records/$id': {
      id: '/_auth/_boss/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AuthBossRecordsIdRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/stats': {
      id: '/_auth/_boss/orders/stats'
      path: '/orders/stats'
      fullPath: '/orders/stats'
      preLoaderRoute: typeof AuthBossOrdersStatsRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/new': {
      id: '/_auth/_boss/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthBossOrdersNewRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/customers/new': {
      id: '/_auth/_boss/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthBossCustomersNewRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/customers/$id': {
      id: '/_auth/_boss/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthBossCustomersIdRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/$id/': {
      id: '/_auth/_boss/orders/$id/'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthBossOrdersIdIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/$id/edit': {
      id: '/_auth/_boss/orders/$id/edit'
      path: '/orders/$id/edit'
      fullPath: '/orders/$id/edit'
      preLoaderRoute: typeof AuthBossOrdersIdEditRouteImport
      parentRoute: typeof AuthBossRoute
    }
  }
}

interface AuthBossRouteChildren {
  AuthBossPendingRoute: typeof AuthBossPendingRoute
  AuthBossWorkshopRoute: typeof AuthBossWorkshopRoute
  AuthBossCustomersIdRoute: typeof AuthBossCustomersIdRoute
  AuthBossCustomersNewRoute: typeof AuthBossCustomersNewRoute
  AuthBossOrdersNewRoute: typeof AuthBossOrdersNewRoute
  AuthBossOrdersStatsRoute: typeof AuthBossOrdersStatsRoute
  AuthBossRecordsIdRoute: typeof AuthBossRecordsIdRoute
  AuthBossRecordsNewRoute: typeof AuthBossRecordsNewRoute
  AuthBossRecordsStatsRoute: typeof AuthBossRecordsStatsRoute
  AuthBossCustomersIndexRoute: typeof AuthBossCustomersIndexRoute
  AuthBossOrdersIndexRoute: typeof AuthBossOrdersIndexRoute
  AuthBossRecordsIndexRoute: typeof AuthBossRecordsIndexRoute
  AuthBossStaffIndexRoute: typeof AuthBossStaffIndexRoute
  AuthBossOrdersIdEditRoute: typeof AuthBossOrdersIdEditRoute
  AuthBossOrdersIdIndexRoute: typeof AuthBossOrdersIdIndexRoute
}

const AuthBossRouteChildren: AuthBossRouteChildren = {
  AuthBossPendingRoute: AuthBossPendingRoute,
  AuthBossWorkshopRoute: AuthBossWorkshopRoute,
  AuthBossCustomersIdRoute: AuthBossCustomersIdRoute,
  AuthBossCustomersNewRoute: AuthBossCustomersNewRoute,
  AuthBossOrdersNewRoute: AuthBossOrdersNewRoute,
  AuthBossOrdersStatsRoute: AuthBossOrdersStatsRoute,
  AuthBossRecordsIdRoute: AuthBossRecordsIdRoute,
  AuthBossRecordsNewRoute: AuthBossRecordsNewRoute,
  AuthBossRecordsStatsRoute: AuthBossRecordsStatsRoute,
  AuthBossCustomersIndexRoute: AuthBossCustomersIndexRoute,
  AuthBossOrdersIndexRoute: AuthBossOrdersIndexRoute,
  AuthBossRecordsIndexRoute: AuthBossRecordsIndexRoute,
  AuthBossStaffIndexRoute: AuthBossStaffIndexRoute,
  AuthBossOrdersIdEditRoute: AuthBossOrdersIdEditRoute,
  AuthBossOrdersIdIndexRoute: AuthBossOrdersIdIndexRoute,
}

const AuthBossRouteWithChildren = AuthBossRoute._addFileChildren(
  AuthBossRouteChildren,
)

interface AuthStaffRouteChildren {
  AuthStaffMyRecordsIdRoute: typeof AuthStaffMyRecordsIdRoute
  AuthStaffMyRecordsNewRoute: typeof AuthStaffMyRecordsNewRoute
  AuthStaffMyRecordsStatsRoute: typeof AuthStaffMyRecordsStatsRoute
  AuthStaffMyRecordsIndexRoute: typeof AuthStaffMyRecordsIndexRoute
}

const AuthStaffRouteChildren: AuthStaffRouteChildren = {
  AuthStaffMyRecordsIdRoute: AuthStaffMyRecordsIdRoute,
  AuthStaffMyRecordsNewRoute: AuthStaffMyRecordsNewRoute,
  AuthStaffMyRecordsStatsRoute: AuthStaffMyRecordsStatsRoute,
  AuthStaffMyRecordsIndexRoute: AuthStaffMyRecordsIndexRoute,
}

const AuthStaffRouteWithChildren = AuthStaffRoute._addFileChildren(
  AuthStaffRouteChildren,
)

interface AuthRouteChildren {
  AuthBossRoute: typeof AuthBossRouteWithChildren
  AuthStaffRoute: typeof AuthStaffRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBossRoute: AuthBossRouteWithChildren,
  AuthStaffRoute: AuthStaffRouteWithChildren,
  AuthProfileRoute: AuthProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterStaffRoute: RegisterStaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
