/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthProcessesRouteImport } from './routes/_auth/processes'
import { Route as AuthStaffRouteImport } from './routes/_auth/_staff'
import { Route as AuthBossRouteImport } from './routes/_auth/_boss'
import { Route as AuthStaffRecordRouteImport } from './routes/_auth/_staff/record'
import { Route as AuthBossPendingRouteImport } from './routes/_auth/_boss/pending'
import { Route as AuthBossOrdersIndexRouteImport } from './routes/_auth/_boss/orders/index'
import { Route as AuthBossCustomersIndexRouteImport } from './routes/_auth/_boss/customers/index'
import { Route as AuthBossOrdersNewRouteImport } from './routes/_auth/_boss/orders/new'
import { Route as AuthBossCustomersNewRouteImport } from './routes/_auth/_boss/customers/new'
import { Route as AuthBossCustomersIdRouteImport } from './routes/_auth/_boss/customers/$id'
import { Route as AuthBossOrdersIdIndexRouteImport } from './routes/_auth/_boss/orders/$id/index'
import { Route as AuthBossOrdersIdEditRouteImport } from './routes/_auth/_boss/orders/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProcessesRoute = AuthProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStaffRoute = AuthStaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBossRoute = AuthBossRouteImport.update({
  id: '/_boss',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStaffRecordRoute = AuthStaffRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthStaffRoute,
} as any)
const AuthBossPendingRoute = AuthBossPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersIndexRoute = AuthBossOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossCustomersIndexRoute = AuthBossCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersNewRoute = AuthBossOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossCustomersNewRoute = AuthBossCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossCustomersIdRoute = AuthBossCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersIdIndexRoute = AuthBossOrdersIdIndexRouteImport.update({
  id: '/orders/$id/',
  path: '/orders/$id/',
  getParentRoute: () => AuthBossRoute,
} as any)
const AuthBossOrdersIdEditRoute = AuthBossOrdersIdEditRouteImport.update({
  id: '/orders/$id/edit',
  path: '/orders/$id/edit',
  getParentRoute: () => AuthBossRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/processes': typeof AuthProcessesRoute
  '/profile': typeof AuthProfileRoute
  '/': typeof AuthIndexRoute
  '/pending': typeof AuthBossPendingRoute
  '/record': typeof AuthStaffRecordRoute
  '/customers/$id': typeof AuthBossCustomersIdRoute
  '/customers/new': typeof AuthBossCustomersNewRoute
  '/orders/new': typeof AuthBossOrdersNewRoute
  '/customers': typeof AuthBossCustomersIndexRoute
  '/orders': typeof AuthBossOrdersIndexRoute
  '/orders/$id/edit': typeof AuthBossOrdersIdEditRoute
  '/orders/$id': typeof AuthBossOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/processes': typeof AuthProcessesRoute
  '/profile': typeof AuthProfileRoute
  '/': typeof AuthIndexRoute
  '/pending': typeof AuthBossPendingRoute
  '/record': typeof AuthStaffRecordRoute
  '/customers/$id': typeof AuthBossCustomersIdRoute
  '/customers/new': typeof AuthBossCustomersNewRoute
  '/orders/new': typeof AuthBossOrdersNewRoute
  '/customers': typeof AuthBossCustomersIndexRoute
  '/orders': typeof AuthBossOrdersIndexRoute
  '/orders/$id/edit': typeof AuthBossOrdersIdEditRoute
  '/orders/$id': typeof AuthBossOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/_boss': typeof AuthBossRouteWithChildren
  '/_auth/_staff': typeof AuthStaffRouteWithChildren
  '/_auth/processes': typeof AuthProcessesRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/_boss/pending': typeof AuthBossPendingRoute
  '/_auth/_staff/record': typeof AuthStaffRecordRoute
  '/_auth/_boss/customers/$id': typeof AuthBossCustomersIdRoute
  '/_auth/_boss/customers/new': typeof AuthBossCustomersNewRoute
  '/_auth/_boss/orders/new': typeof AuthBossOrdersNewRoute
  '/_auth/_boss/customers/': typeof AuthBossCustomersIndexRoute
  '/_auth/_boss/orders/': typeof AuthBossOrdersIndexRoute
  '/_auth/_boss/orders/$id/edit': typeof AuthBossOrdersIdEditRoute
  '/_auth/_boss/orders/$id/': typeof AuthBossOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/processes'
    | '/profile'
    | '/'
    | '/pending'
    | '/record'
    | '/customers/$id'
    | '/customers/new'
    | '/orders/new'
    | '/customers'
    | '/orders'
    | '/orders/$id/edit'
    | '/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/processes'
    | '/profile'
    | '/'
    | '/pending'
    | '/record'
    | '/customers/$id'
    | '/customers/new'
    | '/orders/new'
    | '/customers'
    | '/orders'
    | '/orders/$id/edit'
    | '/orders/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/_boss'
    | '/_auth/_staff'
    | '/_auth/processes'
    | '/_auth/profile'
    | '/_auth/'
    | '/_auth/_boss/pending'
    | '/_auth/_staff/record'
    | '/_auth/_boss/customers/$id'
    | '/_auth/_boss/customers/new'
    | '/_auth/_boss/orders/new'
    | '/_auth/_boss/customers/'
    | '/_auth/_boss/orders/'
    | '/_auth/_boss/orders/$id/edit'
    | '/_auth/_boss/orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/processes': {
      id: '/_auth/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthProcessesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_staff': {
      id: '/_auth/_staff'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthStaffRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_boss': {
      id: '/_auth/_boss'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthBossRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_staff/record': {
      id: '/_auth/_staff/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthStaffRecordRouteImport
      parentRoute: typeof AuthStaffRoute
    }
    '/_auth/_boss/pending': {
      id: '/_auth/_boss/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthBossPendingRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/': {
      id: '/_auth/_boss/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthBossOrdersIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/customers/': {
      id: '/_auth/_boss/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthBossCustomersIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/new': {
      id: '/_auth/_boss/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthBossOrdersNewRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/customers/new': {
      id: '/_auth/_boss/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthBossCustomersNewRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/customers/$id': {
      id: '/_auth/_boss/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthBossCustomersIdRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/$id/': {
      id: '/_auth/_boss/orders/$id/'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthBossOrdersIdIndexRouteImport
      parentRoute: typeof AuthBossRoute
    }
    '/_auth/_boss/orders/$id/edit': {
      id: '/_auth/_boss/orders/$id/edit'
      path: '/orders/$id/edit'
      fullPath: '/orders/$id/edit'
      preLoaderRoute: typeof AuthBossOrdersIdEditRouteImport
      parentRoute: typeof AuthBossRoute
    }
  }
}

interface AuthBossRouteChildren {
  AuthBossPendingRoute: typeof AuthBossPendingRoute
  AuthBossCustomersIdRoute: typeof AuthBossCustomersIdRoute
  AuthBossCustomersNewRoute: typeof AuthBossCustomersNewRoute
  AuthBossOrdersNewRoute: typeof AuthBossOrdersNewRoute
  AuthBossCustomersIndexRoute: typeof AuthBossCustomersIndexRoute
  AuthBossOrdersIndexRoute: typeof AuthBossOrdersIndexRoute
  AuthBossOrdersIdEditRoute: typeof AuthBossOrdersIdEditRoute
  AuthBossOrdersIdIndexRoute: typeof AuthBossOrdersIdIndexRoute
}

const AuthBossRouteChildren: AuthBossRouteChildren = {
  AuthBossPendingRoute: AuthBossPendingRoute,
  AuthBossCustomersIdRoute: AuthBossCustomersIdRoute,
  AuthBossCustomersNewRoute: AuthBossCustomersNewRoute,
  AuthBossOrdersNewRoute: AuthBossOrdersNewRoute,
  AuthBossCustomersIndexRoute: AuthBossCustomersIndexRoute,
  AuthBossOrdersIndexRoute: AuthBossOrdersIndexRoute,
  AuthBossOrdersIdEditRoute: AuthBossOrdersIdEditRoute,
  AuthBossOrdersIdIndexRoute: AuthBossOrdersIdIndexRoute,
}

const AuthBossRouteWithChildren = AuthBossRoute._addFileChildren(
  AuthBossRouteChildren,
)

interface AuthStaffRouteChildren {
  AuthStaffRecordRoute: typeof AuthStaffRecordRoute
}

const AuthStaffRouteChildren: AuthStaffRouteChildren = {
  AuthStaffRecordRoute: AuthStaffRecordRoute,
}

const AuthStaffRouteWithChildren = AuthStaffRoute._addFileChildren(
  AuthStaffRouteChildren,
)

interface AuthRouteChildren {
  AuthBossRoute: typeof AuthBossRouteWithChildren
  AuthStaffRoute: typeof AuthStaffRouteWithChildren
  AuthProcessesRoute: typeof AuthProcessesRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBossRoute: AuthBossRouteWithChildren,
  AuthStaffRoute: AuthStaffRouteWithChildren,
  AuthProcessesRoute: AuthProcessesRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
